/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { requireAdmin } from "@/lib/admin/require-admin";
import { publishListingEdit } from "../../actions";
import styles from "./edit.module.css";

function socialValue(value: unknown, key: string) {
  return value && typeof value === "object" && !Array.isArray(value) && typeof (value as Record<string, unknown>)[key] === "string" ? String((value as Record<string, unknown>)[key]) : "";
}

export default async function AdminEditListingPage({ params, searchParams }: { params: Promise<{ listingId: string }>; searchParams: Promise<{ error?: string }> }) {
  const { listingId } = await params; const query = await searchParams;
  if (!/^[0-9a-f-]{36}$/i.test(listingId)) notFound();
  const { supabase } = await requireAdmin();
  const { data: listing } = await supabase.from("listings").select("current_published_version_id").eq("id", listingId).maybeSingle();
  if (!listing?.current_published_version_id) notFound();
  const [{ data: version }, { data: assignments }, { data: selectedTags }, { data: services }, { data: categories }, { data: tags }, { data: activeUpdate }, { data: image }] = await Promise.all([
    supabase.from("listing_versions").select("*").eq("id", listing.current_published_version_id).maybeSingle(),
    supabase.from("listing_category_assignments").select("category_id, is_primary").eq("listing_version_id", listing.current_published_version_id),
    supabase.from("listing_service_tags").select("service_tag_id").eq("listing_version_id", listing.current_published_version_id),
    supabase.from("listing_services").select("name, sort_order").eq("listing_version_id", listing.current_published_version_id).order("sort_order"),
    supabase.from("categories").select("id, name, description, sort_order").eq("is_active", true).order("sort_order"),
    supabase.from("service_tags").select("id, category_id, name, sort_order").eq("is_active", true).order("sort_order"),
    supabase.from("listing_versions").select("id").eq("listing_id", listingId).in("status", ["draft", "pending"]).limit(1).maybeSingle(),
    supabase.from("listing_images").select("published_storage_path, alt_text").eq("listing_version_id", listing.current_published_version_id).maybeSingle(),
  ]);
  if (!version) notFound();
  if (activeUpdate) redirect(`/admin/listings/${listingId}`);
  const primaryId = assignments?.find((item) => item.is_primary)?.category_id ?? "";
  const additionalIds = new Set(assignments?.filter((item) => !item.is_primary).map((item) => item.category_id));
  const selectedTagIds = new Set(selectedTags?.map((item) => item.service_tag_id));
  const currentImagePath = image?.published_storage_path ?? version.published_image_path;
  const currentImageUrl = currentImagePath ? supabase.storage.from("listing-images-public").getPublicUrl(currentImagePath).data.publicUrl : null;

  return <><Link className={styles.back} href={`/admin/listings/${listingId}`}>← Cancel and return to listing</Link><header className={styles.header}><p>Administrator correction</p><h1>Edit {version.business_name}</h1><span>Saving publishes a new approved version immediately. The current version remains in the audit history.</span></header>
    {query.error ? <p className={styles.error}>{query.error === "incomplete" ? "Complete the required fields and add an edit reason." : query.error === "limits" ? "Check the category, service-tag and service limits." : query.error === "image" ? "The image could not be prepared. Choose a JPG, PNG or WebP file no larger than 5MB." : "The correction could not be published. No public changes were made."}</p> : null}
    <form className={styles.form} action={publishListingEdit} encType="multipart/form-data"><input type="hidden" name="listingId" value={listingId}/>
      <section><h2>Listing image</h2>{currentImageUrl ? <img src={currentImageUrl} alt={image?.alt_text || "Current listing image"} style={{ width: "min(100%, 18rem)", aspectRatio: "1", borderRadius: ".8rem", objectFit: "cover" }}/> : <p>The standard Service Plaza placeholder is currently in use.</p>}<label>{currentImageUrl ? "Replace image" : "Add image"} <span>(optional)</span><input type="file" name="image" accept="image/jpeg,image/png,image/webp"/></label><p>Minimum recommended: 600 × 600 px. Preferred: 1200 × 1200 px. Maximum 5MB.</p><label>Image description <span>(used when adding or replacing an image)</span><input name="imageAltText" maxLength={300} defaultValue={image?.alt_text ?? ""}/></label>{currentImageUrl ? <label className={styles.check}><input type="checkbox" name="removeImage"/><span>Remove the current image and use the standard placeholder</span></label> : null}</section>
      <section><h2>Basic information and services</h2><label>Business name<input name="businessName" maxLength={160} required defaultValue={version.business_name}/></label><label>Primary category<select name="primaryCategoryId" required defaultValue={primaryId}><option value="">Choose a category</option>{categories?.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><fieldset><legend>Additional categories <span>(up to two)</span></legend><div className={styles.checkGrid}>{categories?.map((category) => <label className={styles.check} key={category.id}><input type="checkbox" name="additionalCategoryIds" value={category.id} defaultChecked={additionalIds.has(category.id)}/><span>{category.name}</span></label>)}</div></fieldset><fieldset><legend>Service tags <span>(up to eight)</span></legend><div className={styles.tagGroups}>{categories?.map((category) => { const categoryTags = tags?.filter((tag) => tag.category_id === category.id) ?? []; return categoryTags.length ? <details key={category.id}><summary>{category.name}</summary><div className={styles.checkGrid}>{categoryTags.map((tag) => <label className={styles.check} key={tag.id}><input type="checkbox" name="serviceTagIds" value={tag.id} defaultChecked={selectedTagIds.has(tag.id)}/><span>{tag.name}</span></label>)}</div></details> : null; })}</div></fieldset><label>Services offered <span>(one per line, up to 15)</span><textarea name="customServices" rows={6} defaultValue={services?.map((service) => service.name).join("\n")}/></label></section>
      <section><h2>About the business</h2><label>Short summary<input name="shortSummary" maxLength={160} required defaultValue={version.short_summary}/></label><label>Full description <span>(at least 100 characters)</span><textarea name="fullDescription" rows={10} maxLength={2000} required defaultValue={version.full_description}/></label><label>Meet the founder <span>(optional)</span><textarea name="founderStory" rows={8} maxLength={2000} defaultValue={version.founder_story ?? ""}/></label></section>
      <section><h2>Public contact information</h2><label>Contact name<input name="publicContactName" maxLength={120} required defaultValue={version.public_contact_name ?? ""}/></label><div className={styles.two}><label>Email<input type="email" name="publicEmail" maxLength={320} defaultValue={version.public_email ?? ""}/></label><label>Telephone<input name="publicPhone" maxLength={40} defaultValue={version.public_phone ?? ""}/></label></div><div className={styles.checkGrid}><label className={styles.check}><input type="checkbox" name="showPublicEmail" defaultChecked={version.show_public_email}/><span>Display email publicly</span></label><label className={styles.check}><input type="checkbox" name="showPublicPhone" defaultChecked={version.show_public_phone}/><span>Display telephone publicly</span></label></div><label>Website<input type="url" name="websiteUrl" defaultValue={version.website_url ?? ""}/></label><div className={styles.two}>{["instagram", "facebook", "linkedin", "tiktok", "youtube"].map((network) => <label key={network}>{network[0].toUpperCase() + network.slice(1)}<input type="url" name={network} defaultValue={socialValue(version.social_links, network)}/></label>)}</div></section>
      <section><h2>How and where they work</h2><label className={styles.check}><input type="checkbox" name="isUkBased" defaultChecked={version.is_uk_based}/><span>Confirmed as a UK-based business</span></label><div className={styles.checkGrid}><label className={styles.check}><input type="checkbox" name="offersOnline" defaultChecked={version.offers_online}/><span>Online</span></label><label className={styles.check}><input type="checkbox" name="offersInPerson" defaultChecked={version.offers_in_person}/><span>In person</span></label></div><p>The business base postcode remains private. A separate customer address is published only when confirmed below.</p><div className={styles.two}><label>Private business postcode<input name="businessPostcode" maxLength={8} defaultValue={version.business_postcode ?? ""}/></label><label>In-person arrangement<select name="inPersonMode" defaultValue={version.in_person_mode ?? ""}><option value="">Choose one</option><option value="travels_to_customer">Travels to customers</option><option value="customers_visit">Customers visit</option><option value="both">Both</option></select></label><label>Travel radius<select name="travelRadiusMiles" defaultValue={version.travel_radius_miles ?? 30}>{[1,2,5,10,20,30,50,75,100,125,150].map((miles)=><option value={miles} key={miles}>{miles} miles</option>)}</select></label></div><label>Full public customer address<textarea name="publicVisitAddress" rows={5} maxLength={500} defaultValue={version.public_visit_address ?? ""}/></label><label className={styles.check}><input type="checkbox" name="publicVisitAddressConfirmed" defaultChecked={version.public_visit_address_confirmed}/><span>Confirmed for public display when customers visit</span></label><label className={styles.check}><input type="checkbox" name="inPersonNationwide" defaultChecked={version.in_person_nationwide}/><span>Travels to customers nationwide</span></label></section>
      <section><h2>Plaza Perk</h2><label className={styles.check}><input type="checkbox" name="hasPlazaPerk" defaultChecked={version.has_plaza_perk}/><span>Include a Plaza Perk</span></label><label>Perk title<input name="perkTitle" maxLength={160} defaultValue={version.perk_title ?? ""}/></label><label>Perk description<textarea name="perkDescription" rows={5} maxLength={1000} defaultValue={version.perk_description ?? ""}/></label><label>How to claim<textarea name="perkRedemption" rows={4} maxLength={1000} defaultValue={version.perk_redemption ?? ""}/></label><label>Conditions<textarea name="perkConditions" rows={3} maxLength={1000} defaultValue={version.perk_conditions ?? ""}/></label><label>Expiry date<input type="date" name="perkExpiresOn" defaultValue={version.perk_expires_on ?? ""}/></label></section>
      <section className={styles.publish}><h2>Publish correction</h2><label>Reason for the administrator edit <span>(private audit note)</span><textarea name="reason" rows={4} maxLength={2000} required/></label><p>The business owner’s approved listing will be updated immediately. This note is not shown publicly.</p><div><Link href={`/admin/listings/${listingId}`}>Cancel</Link><button type="submit">Publish corrected version</button></div></section>
    </form></>;
}
