/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/admin/require-admin";
import { editPendingApplication, removePendingApplicationImage, updatePendingApplicationImage } from "../../actions";
import styles from "../../../listings/[listingId]/edit/edit.module.css";

function socialValue(value: unknown, key: string) {
  return value && typeof value === "object" && !Array.isArray(value) && typeof (value as Record<string, unknown>)[key] === "string" ? String((value as Record<string, unknown>)[key]) : "";
}

export default async function EditPendingApplicationPage({ params, searchParams }: { params: Promise<{ versionId: string }>; searchParams: Promise<{ error?: string; notice?: string }> }) {
  const { versionId } = await params; const query = await searchParams;
  if (!/^[0-9a-f-]{36}$/i.test(versionId)) notFound();
  const { supabase } = await requireAdmin();
  const [{ data: version }, { data: services }, { data: image }] = await Promise.all([
    supabase.from("listing_versions").select("*").eq("id", versionId).eq("status", "pending").maybeSingle(),
    supabase.from("listing_services").select("name, sort_order").eq("listing_version_id", versionId).order("sort_order"),
    supabase.from("listing_images").select("private_storage_path, original_filename, mime_type, byte_size, width, height, alt_text").eq("listing_version_id", versionId).maybeSingle(),
  ]);
  if (!version) notFound();
  const { data: signed } = image ? await supabase.storage.from("listing-images-private").createSignedUrl(image.private_storage_path, 3600) : { data: null };
  return <><Link className={styles.back} href={`/admin/applications/${versionId}`}>← Cancel and return to review</Link><header className={styles.header}><p>Administrator correction</p><h1>Edit {version.business_name}</h1><span>These changes update the submitted application without publishing it. You will return to the review page to make a separate decision.</span></header>
    {query.error ? <p className={styles.error}>{query.error === "incomplete" ? "Complete the required fields and add an edit reason." : query.error === "limits" ? "Check the service limits and edit reason." : query.error === "image" ? "The image change could not be saved. Check that the file is a JPG, PNG or WebP no larger than 5MB." : "The corrections could not be saved. The submitted application was not changed."}</p> : null}
    {query.notice ? <p style={{ padding: "1rem", borderRadius: ".6rem", background: "#eef5f1", color: "#304f3d" }}>{query.notice === "image_removed" ? "Image removed. The standard placeholder will be used if you approve this listing." : "Image changes saved."}</p> : null}
    <form className={styles.form} action={updatePendingApplicationImage} encType="multipart/form-data"><input type="hidden" name="versionId" value={versionId}/><section><h2>Submitted image</h2>{signed?.signedUrl ? <img src={signed.signedUrl} alt={image?.alt_text || "Submitted business image"} style={{ width: "min(100%, 18rem)", aspectRatio: "1", borderRadius: ".8rem", objectFit: "cover" }}/> : <p>No image is attached. The standard Service Plaza placeholder will be used.</p>}{image ? <p>{image.original_filename} · {image.width ?? "Unknown"} × {image.height ?? "Unknown"} px · {(image.byte_size / 1024).toFixed(1)} KB</p> : null}<label>Replace image <span>(optional)</span><input type="file" name="image" accept="image/jpeg,image/png,image/webp"/></label><p>Minimum recommended: 600 × 600 px. Preferred: 1200 × 1200 px. JPG, PNG or WebP; maximum 5MB.</p><label>Image description <span>(optional)</span><input name="altText" maxLength={300} defaultValue={image?.alt_text ?? ""}/></label><div style={{ display: "flex", gap: ".75rem", flexWrap: "wrap" }}><button type="submit">{image ? "Save image changes" : "Add image"}</button>{image ? <button type="submit" formAction={removePendingApplicationImage} style={{ background: "#873b35" }}>Remove image and use placeholder</button> : null}</div></section></form>
    <form className={styles.form} action={editPendingApplication}><input type="hidden" name="versionId" value={versionId}/>
      <section><h2>Basic information and services</h2><label>Business name<input name="businessName" maxLength={160} required defaultValue={version.business_name}/></label><label>Services offered <span>(one per line, up to 15)</span><textarea name="customServices" rows={6} defaultValue={services?.map((service) => service.name).join("\n")}/></label><p>Categories and service tags remain as submitted. Use a change request if those selections need to change.</p></section>
      <section><h2>About the business</h2><label>Short summary<input name="shortSummary" maxLength={160} required defaultValue={version.short_summary}/></label><label>Full description <span>(at least 100 characters)</span><textarea name="fullDescription" rows={10} maxLength={2000} required defaultValue={version.full_description}/></label></section>
      <section><h2>Public contact information</h2><label>Contact name<input name="publicContactName" maxLength={120} required defaultValue={version.public_contact_name ?? ""}/></label><div className={styles.two}><label>Email<input type="email" name="publicEmail" maxLength={320} defaultValue={version.public_email ?? ""}/></label><label>Telephone<input name="publicPhone" maxLength={40} defaultValue={version.public_phone ?? ""}/></label></div><div className={styles.checkGrid}><label className={styles.check}><input type="checkbox" name="showPublicEmail" defaultChecked={version.show_public_email}/><span>Display email publicly</span></label><label className={styles.check}><input type="checkbox" name="showPublicPhone" defaultChecked={version.show_public_phone}/><span>Display telephone publicly</span></label></div><label>Website<input type="url" name="websiteUrl" defaultValue={version.website_url ?? ""}/></label><div className={styles.two}>{["instagram", "facebook", "linkedin", "tiktok", "youtube"].map((network) => <label key={network}>{network[0].toUpperCase() + network.slice(1)}<input type="url" name={network} defaultValue={socialValue(version.social_links, network)}/></label>)}</div></section>
      <section><h2>How and where they work</h2><label className={styles.check}><input type="checkbox" name="isUkBased" defaultChecked={version.is_uk_based}/><span>Confirmed as a UK-based business</span></label><div className={styles.checkGrid}><label className={styles.check}><input type="checkbox" name="offersOnline" defaultChecked={version.offers_online}/><span>Online</span></label><label className={styles.check}><input type="checkbox" name="offersInPerson" defaultChecked={version.offers_in_person}/><span>In person</span></label></div><div className={styles.two}><label>Base town or city (optional)<input name="baseTownCity" maxLength={120} defaultValue={version.base_town_city ?? ""}/></label><label>County or region (optional)<input name="ukRegion" maxLength={120} defaultValue={version.uk_region ?? ""}/></label></div></section>
      <section><h2>Plaza Perk</h2><label className={styles.check}><input type="checkbox" name="hasPlazaPerk" defaultChecked={version.has_plaza_perk}/><span>Include a Plaza Perk</span></label><label>Perk title<input name="perkTitle" maxLength={160} defaultValue={version.perk_title ?? ""}/></label><label>Perk description<textarea name="perkDescription" rows={5} maxLength={1000} defaultValue={version.perk_description ?? ""}/></label><label>How to claim<textarea name="perkRedemption" rows={4} maxLength={1000} defaultValue={version.perk_redemption ?? ""}/></label><label>Conditions<textarea name="perkConditions" rows={3} maxLength={1000} defaultValue={version.perk_conditions ?? ""}/></label><label>Expiry date<input type="date" name="perkExpiresOn" defaultValue={version.perk_expires_on ?? ""}/></label></section>
      <section className={styles.publish}><h2>Save administrator corrections</h2><label>Reason for the edit <span>(private audit note)</span><textarea name="reason" rows={3} maxLength={2000} required placeholder="For example: Corrected spelling in the short summary."/></label><p>This does not approve or publish the listing and does not send an email to the business.</p><div><Link href={`/admin/applications/${versionId}`}>Cancel</Link><button type="submit">Save corrections</button></div></section>
    </form></>;
}
