-- Agreed launch taxonomy: eight specific service tags per top-level category.
with tags(category_slug, name, slug, sort_order) as (values
('business-administrative-support','Virtual Assistance','virtual-assistance',10),
('business-administrative-support','General Administration','general-administration',20),
('business-administrative-support','Online Business Management','online-business-management',30),
('business-administrative-support','Operations Management','operations-management',40),
('business-administrative-support','Project Management','project-management',50),
('business-administrative-support','Customer Support','customer-support',60),
('business-administrative-support','Research & Data Entry','research-data-entry',70),
('business-administrative-support','Bookkeeping Support','bookkeeping-support',80),
('marketing-sales-pr','Social Media Management','social-media-management',10),
('marketing-sales-pr','Content Marketing','content-marketing',20),
('marketing-sales-pr','Email Marketing','email-marketing',30),
('marketing-sales-pr','Search Engine Optimisation (SEO)','search-engine-optimisation',40),
('marketing-sales-pr','Paid Advertising','paid-advertising',50),
('marketing-sales-pr','Lead Generation','lead-generation',60),
('marketing-sales-pr','Sales Support','sales-support',70),
('marketing-sales-pr','Public Relations','public-relations',80),
('web-tech-digital-services','Web Design','web-design',10),
('web-tech-digital-services','Web Development','web-development',20),
('web-tech-digital-services','E-commerce','e-commerce',30),
('web-tech-digital-services','UX & UI Design','ux-ui-design',40),
('web-tech-digital-services','Automation & Integrations','automation-integrations',50),
('web-tech-digital-services','CRM Setup & Support','crm-setup-support',60),
('web-tech-digital-services','IT Support','it-support',70),
('web-tech-digital-services','Cybersecurity','cybersecurity',80),
('design-content-photography','Graphic Design','graphic-design',10),
('design-content-photography','Brand Identity','brand-identity',20),
('design-content-photography','Copywriting','copywriting',30),
('design-content-photography','Content Writing','content-writing',40),
('design-content-photography','Photography','photography',50),
('design-content-photography','Videography','videography',60),
('design-content-photography','Video Editing','video-editing',70),
('design-content-photography','Illustration','illustration',80),
('coaching-consulting-careers','Business Coaching','business-coaching',10),
('coaching-consulting-careers','Life Coaching','life-coaching',20),
('coaching-consulting-careers','Executive Coaching','executive-coaching',30),
('coaching-consulting-careers','Career Coaching','career-coaching',40),
('coaching-consulting-careers','Leadership Development','leadership-development',50),
('coaching-consulting-careers','Business Consulting','business-consulting',60),
('coaching-consulting-careers','Mentoring','mentoring',70),
('coaching-consulting-careers','CV & Interview Support','cv-interview-support',80),
('education-tutoring','Primary Tutoring','primary-tutoring',10),
('education-tutoring','Secondary & GCSE Tutoring','secondary-gcse-tutoring',20),
('education-tutoring','A-Level Tutoring','a-level-tutoring',30),
('education-tutoring','SEND Tutoring','send-tutoring',40),
('education-tutoring','Language Teaching','language-teaching',50),
('education-tutoring','Music Teaching','music-teaching',60),
('education-tutoring','Professional Training','professional-training',70),
('education-tutoring','Course & Workshop Delivery','course-workshop-delivery',80),
('health-therapy-wellbeing','Counselling','counselling',10),
('health-therapy-wellbeing','Psychotherapy','psychotherapy',20),
('health-therapy-wellbeing','Hypnotherapy','hypnotherapy',30),
('health-therapy-wellbeing','Nutrition','nutrition',40),
('health-therapy-wellbeing','Personal Training','personal-training',50),
('health-therapy-wellbeing','Yoga & Pilates','yoga-pilates',60),
('health-therapy-wellbeing','Massage Therapy','massage-therapy',70),
('health-therapy-wellbeing','Holistic Therapies','holistic-therapies',80),
('beauty-aesthetics','Beauty Therapy','beauty-therapy',10),
('beauty-aesthetics','Makeup Artistry','makeup-artistry',20),
('beauty-aesthetics','Hair Services','hair-services',30),
('beauty-aesthetics','Nail Services','nail-services',40),
('beauty-aesthetics','Skincare & Facials','skincare-facials',50),
('beauty-aesthetics','Brows & Lashes','brows-lashes',60),
('beauty-aesthetics','Aesthetic Treatments','aesthetic-treatments',70),
('beauty-aesthetics','Mobile Beauty Services','mobile-beauty-services',80),
('travel-experiences','Travel Planning','travel-planning',10),
('travel-experiences','Bespoke Itineraries','bespoke-itineraries',20),
('travel-experiences','Honeymoons','honeymoons',30),
('travel-experiences','Group Travel','group-travel',40),
('travel-experiences','Luxury Travel','luxury-travel',50),
('travel-experiences','Accessible Travel','accessible-travel',60),
('travel-experiences','Tours & Experiences','tours-experiences',70),
('travel-experiences','Retreats','retreats',80),
('events-celebrations','Event Planning','event-planning',10),
('events-celebrations','Wedding Planning','wedding-planning',20),
('events-celebrations','Celebrants','celebrants',30),
('events-celebrations','Entertainment','entertainment',40),
('events-celebrations','Venue Services','venue-services',50),
('events-celebrations','Catering','catering',60),
('events-celebrations','Floristry & Styling','floristry-styling',70),
('events-celebrations','Event Photography & Video','event-photography-video',80),
('finance-legal-professional-services','Accounting','accounting',10),
('finance-legal-professional-services','Bookkeeping & Payroll','bookkeeping-payroll',20),
('finance-legal-professional-services','Tax Services','tax-services',30),
('finance-legal-professional-services','Financial Advice','financial-advice',40),
('finance-legal-professional-services','Mortgage & Insurance Advice','mortgage-insurance-advice',50),
('finance-legal-professional-services','Legal Services','legal-services',60),
('finance-legal-professional-services','Human Resources','human-resources',70),
('finance-legal-professional-services','Compliance & Governance','compliance-governance',80),
('personal-family-lifestyle-services','Personal Styling','personal-styling',10),
('personal-family-lifestyle-services','Professional Organising','professional-organising',20),
('personal-family-lifestyle-services','Parenting Support','parenting-support',30),
('personal-family-lifestyle-services','Family Support','family-support',40),
('personal-family-lifestyle-services','Pet Services','pet-services',50),
('personal-family-lifestyle-services','Home Management','home-management',60),
('personal-family-lifestyle-services','Personal Concierge','personal-concierge',70),
('personal-family-lifestyle-services','Errand Services','errand-services',80)
)
insert into public.service_tags(category_id,name,slug,sort_order)
select c.id,t.name,t.slug,t.sort_order from tags t
join public.categories c on c.slug=t.category_slug;

create function private.enforce_service_tag_limit()
returns trigger language plpgsql set search_path='' as $$
begin
  if (select count(*) >= 8 from public.listing_service_tags
      where listing_version_id=new.listing_version_id) then
    raise exception 'A listing version may have no more than eight service tags';
  end if;
  return new;
end;
$$;
create trigger enforce_service_tag_limit before insert on public.listing_service_tags
for each row execute function private.enforce_service_tag_limit();
revoke all on function private.enforce_service_tag_limit() from public;
